# Set global platform target to iOS 14.0
platform :ios, '14.0'

# Ignore CocoaPods warnings
source 'https://github.com/CocoaPods/Specs.git'

# Standard Flutter integration
flutter_root = File.expand_path('..', File.dirname(__FILE__))
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# Force every installed plugin to build with iOS 14.0
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end