// lib/constants/product_constants.dart

class ProductConstants {
  /// Predefined delivery timeframe options
  static const List<String> deliveryOptions = [
    'Within 24 Hours',
    '1 - 2 Business Days',
    '3 - 5 Business Days',
    '1 - 2 Weeks (Imported)',
    '2 - 4 Weeks (Imported)',
  ];

  /// Primary list of master categories
  static const List<String> categories = [
    "Electronics",
    "Groceries",
    "Fashion",
    "Home & Living",
    "Beauty & Personal Care",
    "Health & Wellness",
    "Agriculture",
    "Vehicles",
    "Construction & Hardware",
    "Books & Education",
    "Sports & Outdoors",
    "Baby & Kids",
    "Food & Beverages",
    "Pets & Animals",
    "Office Supplies",
    "Entertainment",
    "Services",
    "Industrial Equipment",
    "Other", // Custom Category Support
  ];

  /// Category Dynamic Attribute Fields Mapping
  static const Map<String, List<String>> categoryFields = {
    'Fashion': ['Color', 'Size', 'Material'],
    'Electronics': ['Color', 'Storage', 'RAM'],
    'Groceries': ['Weight', 'Pack Size'],
    'Vehicles': ['Color', 'Transmission', 'Engine'],
    'Agriculture': ['Weight', 'Variety'],
    'Books & Education': ['Format', 'Language'],
    'Food & Beverages': ['Weight', 'Flavor'],
    'Other': ['Color', 'Size', 'Variant'],
  };

  /// Structural SubCategory & Brands Mapping with Global Brand Coverage
  static const Map<String, Map<String, List<String>>> categorySubCategoryBrands = {
    'Electronics': {
      'Smartphones': ['Apple','Tecno','Infinix','itel', 'Samsung', 'Xiaomi', 'Google', 'OnePlus', 'Oppo', 'Vivo', 'Realme', 'Motorola', 'Nokia', 'Honor', 'Other'],
      'Tablets': ['Apple (iPad)', 'Samsung Galaxy Tab', 'Lenovo Tab', 'Amazon Fire', 'Microsoft Surface', 'Xiaomi Pad', 'Other'],
      'Laptops': ['Lenovo', 'Dell', 'HP', 'Apple MacBook', 'ASUS', 'Acer', 'MSI', 'Razer', 'Samsung', 'Microsoft', 'Other'],
      'Desktop Computers': ['Dell', 'HP', 'Apple iMac', 'Lenovo ThinkCentre', 'ASUS', 'Acer', 'Corsair', 'Other'],
      'Computer Accessories': ['Logitech', 'Razer', 'Corsair', 'Anker', 'SteelSeries', 'HyperX', 'Keychron', 'Other'],
      'Printers & Scanners': ['HP', 'Canon', 'Epson', 'Brother', 'Xerox', 'Ricoh', 'Other'],
      'Networking Equipment': ['Cisco', 'TP-Link', 'Netgear', 'ASUS', 'Ubiquiti', 'D-Link', 'MikroTik', 'Other'],
      'Televisions': ['Samsung', 'LG', 'Sony', 'TCL', 'Hisense', 'Panasonic', 'Philips', 'Vizio', 'Other'],
      'Audio Systems': ['Bose', 'Sony', 'JBL', 'Sonos', 'Sennheiser', 'Audio-Technica', 'Beats', 'Marshall', 'Other'],
      'Cameras': ['Canon', 'Nikon', 'Sony', 'Fujifilm', 'GoPro', 'Panasonic', 'DJI', 'Olympus', 'Other'],
      'Smart Watches': ['Apple Watch', 'Samsung Galaxy Watch', 'Garmin', 'Fitbit', 'Amazfit', 'Huawei', 'Other'],
      'Gaming Consoles': ['Sony PlayStation', 'Microsoft Xbox', 'Nintendo Switch', 'Valve Steam Deck', 'Other'],
      'Gaming Accessories': ['Razer', 'Logitech G', 'SteelSeries', 'HyperX', 'Corsair', 'ASTRO', 'Other'],
      'Mobile Accessories': ['Anker', 'Belkin', 'Spigen', 'OtterBox', 'Baseus', 'Ugreen', 'Other'],
      'Storage Devices': ['SanDisk', 'Samsung', 'Western Digital', 'Seagate', 'Kingston', 'Crucial', 'Other'],
      'Power Banks': ['Anker', 'RAVPower', 'Xiaomi', 'Belkin', 'Baseus', 'Romoss', 'Other'],
      'Chargers & Cables': ['Belkin', 'Anker', 'Apple', 'Samsung', 'Baseus', 'Ugreen', 'Other'],
      'Home Appliances': ['LG', 'Samsung', 'Whirlpool', 'Bosch', 'Haier', 'Panasonic', 'Midea', 'Other'],
      'Kitchen Appliances': ['Philips', 'Instant Pot', 'KitchenAid', 'Cuisinart', 'Ninja', 'Breville', 'DeLonghi', 'Other'],
      'Smart Home Devices': ['Google Nest', 'Amazon Echo', 'Philips Hue', 'Ring', 'Arlo', 'TP-Link Kasa', 'Other'],
      'Other': ['Other'],
    },
    'Groceries': {
      'Rice & Grains': ["Ben's Original", 'Mahatma', 'Tilda', 'Lundberg', 'Royal', 'Other'],
      'Flour': ['Gold Medal', 'King Arthur', 'Pillsbury', 'Bob\'s Red Mill', 'Other'],
      'Cooking Oil': ['Crisco', 'Wesson', 'Bertolli', 'Mazola', 'Filippo Berio', 'Other'],
      'Sugar': ['Domino Sugar', 'C&H', 'In the Raw', 'Tate & Lyle', 'Other'],
      'Salt & Spices': ['McCormick', 'Morton Salt', 'Badia', 'Simply Organic', 'Lawry\'s', 'Other'],
      'Pasta & Noodles': ['Barilla', 'De Cecco', 'Ronzoni', 'Nissin', 'Maruchan', 'Indomie', 'Other'],
      'Breakfast Foods': ["Kellogg's", 'General Mills', 'Quaker Oats', 'Post', 'Weetabix', 'Other'],
      'Canned Foods': ['Heinz', 'Campbell\'s', 'Del Monte', 'Green Giant', 'Progresso', 'Other'],
      'Snacks': ["Lay's", 'Doritos', 'Pringles', 'Cheetos', 'Ruffles', 'Takis', 'Other'],
      'Biscuits': ['Oreo', 'McVitie\'s', 'Chips Ahoy!', 'Belvita', 'Lotus Biscoff', 'Other'],
      'Dairy Products': ['Kraft', 'Land O\'Lakes', 'Horizon Organic', 'Chobani', 'President', 'Other'],
      'Eggs': ["Eggland's Best", 'Happy Egg Co.', 'Vital Farms', 'Other'],
      'Frozen Foods': ['Birds Eye', 'Amy\'s Kitchen', 'Stouffer\'s', 'Digiorno', 'McCain', 'Other'],
      'Fresh Vegetables': ['Dole', 'Fresh Express', 'Organic Girl', 'Other'],
      'Fresh Fruits': ['Chiquita', 'Dole', 'Driscoll\'s', 'Del Monte', 'Other'],
      'Meat & Poultry': ['Tyson Foods', 'Perdue', 'Pilgrim\'s', 'Applegate', 'Other'],
      'Seafood': ['Bumble Bee', 'StarKist', 'Chicken of the Sea', 'Gorton\'s', 'Other'],
      'Cleaning Supplies': ['Clorox', 'Lysol', 'Mr. Clean', 'Method', 'Dettol', 'Cif', 'Other'],
      'Household Essentials': ['Procter & Gamble (P&G)', 'Kimberly-Clark', 'Unilever', 'Colgate-Palmolive', 'Other'],
      'Other': ['Other'],
    },
    'Fashion': {
      'Shirts': ['Ralph Lauren', 'Tommy Hilfiger', 'Calvin Klein', 'Brooks Brothers', 'Lacoste', 'Arrow', 'H&M', 'Zara', 'Other'],
      'T-Shirts': ['Hanes', 'Gildan', 'Fruit of the Loom', 'Champion', 'Nike', 'Adidas', 'Uniqlo', 'Levi\'s', 'Other'],
      'Trousers': ['Dockers', 'Levi\'s', 'H&M', 'Zara', 'Wrangler', 'Dickies', 'Chinos', 'Other'],
      'Jeans': ['Levi\'s', 'Wrangler', 'Lee', 'Diesel', 'Pepe Jeans', 'G-Star RAW', 'CK Jeans', 'Other'],
      'Suits': ['Hugo Boss', 'Armani', 'Ted Baker', 'Zara Suit', 'Zegna', 'Brooks Brothers', 'Other'],
      'Jackets': ['The North Face', 'Patagonia', 'Columbia', 'Arc\'teryx', 'Canada Goose', 'Moncler', 'Carhartt', 'Other'],
      'Shoes': [
        'Nike', 'Jordan', 'Adidas', 'Puma', 'Reebok', 'New Balance',
        'ASICS', 'Skechers', 'Converse', 'Vans', 'Fila', 'Under Armour',
        'Timberland', 'Clarks', 'Crocs', 'Birkenstock', 'Dr. Martens', 'Bata', 'Other'
      ],
      'Sandals': ['Birkenstock', 'Crocs', 'Teva', 'Chacos', 'Keen', 'Clarks', 'Havaianas', 'Other'],
      'Watches': ['Rolex', 'Seiko', 'Casio', 'Omega', 'Fossil', 'Citizen', 'Tissot', 'TAG Heuer', 'Timex', 'Other'],
      'Bags': ['Samsonite', 'Herschel', 'Tumi', 'American Tourister', 'Eastpak', 'JanSport', 'Other'],
      'Dresses': ['Zara', 'H&M', 'Mango', 'ASOS', 'Forever 21', 'SHEIN', 'Other'],
      'Tops': ['H&M', 'Zara', 'Forever 21', 'Express', 'Uniqlo', 'Mango', 'Other'],
      'Skirts': ['ASOS', 'Zara', 'H&M', 'Mango', 'Forever 21', 'Other'],
      'Handbags': ['Louis Vuitton', 'Michael Kors', 'Coach', 'Gucci', 'Kate Spade', 'Prada', 'Chanel', 'Hermès', 'Other'],
      'Heels': ['Jimmy Choo', 'Christian Louboutin', 'Steve Madden', 'Nine West', 'Aldo', 'Manolo Blahnik', 'Other'],
      'Jewelry': ['Tiffany & Co.', 'Pandora', 'Swarovski', 'Cartier', 'Bvlgari', 'Other'],
      'Boys Clothing': ['Carter\'s', 'OshKosh B\'gosh', 'The Children\'s Place', 'Gap Kids', 'Nike Kids', 'Other'],
      'Girls Clothing': ['Gap Kids', 'Carter\'s', 'H&M Kids', 'Gymboree', 'Zara Kids', 'Other'],
      'School Uniforms': ['French Toast', 'Lands\' End', 'School Apparel', 'Trutex', 'Other'],
      'Underwear': ['Calvin Klein', 'Hanes', 'Victoria\'s Secret', 'Fruit of the Loom', 'Jockey', 'Savage X Fenty', 'Other'],
      'Sportswear': ['Adidas', 'Nike', 'Under Armour', 'Puma', 'Lululemon', 'Reebok', 'ASICS', 'Gymshark', 'Other'],
      'Traditional Wear': ['Manyavar', 'Fabindia', 'Biba', 'W for Woman', 'Other'],
      'Hats & Caps': ['New Era', 'Adidas', 'Nike', 'Carhartt', 'Puma', 'Under Armour', 'Other'],
      'Sunglasses': ['Ray-Ban', 'Oakley', 'Gucci', 'Prada', 'Persol', 'Maui Jim', 'Other'],
      'Belts': ['Gucci', 'Hermes', 'Levi\'s', 'Tommy Hilfiger', 'Calvin Klein', 'Other'],
      'Other': ['Other'],
    },
    'Home & Living': {
      'Furniture': ['IKEA', 'Ashley Furniture', 'Wayfair', 'La-Z-Boy', 'West Elm', 'Ethan Allen', 'Other'],
      'Bedding': ['Brooklinen', 'Boll & Branch', 'Utopia Bedding', 'Parachute', 'Other'],
      'Curtains': ['Pottery Barn', 'West Elm', 'IKEA Curtains', 'Other'],
      'Carpets & Rugs': ['Safavieh', 'Ruggable', 'Mohawk Home', 'Oriental Weavers', 'Other'],
      'Kitchenware': ['Pyrex', 'OXO', 'Tupperware', 'Corelle', 'Rubbermaid', 'Other'],
      'Cookware': ['Le Creuset', 'Calphalon', 'T-fal', 'Lodge', 'All-Clad', 'Cuisinart', 'Other'],
      'Dining Sets': ['Corelle', 'Lenox', 'Fiesta', 'Gibson', 'Villeroy & Boch', 'Other'],
      'Home Decor': ['West Elm', 'HomeGoods', 'Target Threshold', 'Crate & Barrel', 'Other'],
      'Lighting': ['Philips Hue', 'GE Lighting', 'Lutron', 'Sylvania', 'Other'],
      'Storage & Organization': ['Tupperware', 'Rubbermaid', 'The Container Store', 'IKEA', 'Other'],
      'Bathroom Accessories': ['Kohler', 'Moen', 'Delta Faucet', 'American Standard', 'Other'],
      'Cleaning Equipment': ['Dyson', 'Shark', 'Bissell', 'iRobot Roomba', 'Hoover', 'Other'],
      'Garden Furniture': ['Tuuci', 'Brown Jordan', 'Keter', 'Mainstays', 'Other'],
      'Mattresses': ['Tempur-Pedic', 'Casper', 'Sealy', 'Serta', 'Purple', 'Beautyrest', 'Other'],
      'Other': ['Other'],
    },
    'Beauty & Personal Care': {
      'Makeup': ['MAC Cosmetics', 'Maybelline', "L'Oréal", 'Fenty Beauty', 'Estée Lauder', 'NARS', 'Urban Decay', 'Clinique', 'Other'],
      'Skincare': ['The Ordinary', 'CeraVe', 'Neutrogena', 'Clinique', 'La Roche-Posay', 'Paula\'s Choice', 'Kiehl\'s', 'Other'],
      'Hair Care': ['Olaplex', 'Pantenes', "L'Oréal Professionnel", 'Redken', 'Tresemmé', 'Garnier', 'Other'],
      'Hair Extensions': ['Bellami Hair', 'Zala', 'Luxy Hair', 'Other'],
      'Perfumes': ['Chanel', 'Dior', 'Gucci', 'Tom Ford', 'Versace', 'Yves Saint Laurent', 'Creed', 'Other'],
      'Deodorants': ['Dove', 'Old Spice', 'Secret', 'Degree', 'Native', 'Nivea', 'Other'],
      'Bath & Body': ['Bath & Body Works', 'Aveeno', 'Nivea', 'Lush', 'The Body Shop', 'Other'],
      'Men\'s Grooming': ['Jack Black', 'Baxter of California', 'Bevel', 'Every Man Jack', 'Other'],
      'Shaving Supplies': ['Gillette', 'Harry\'s', 'Dollar Shave Club', 'Braun', 'Philips Norelco', 'Other'],
      'Nail Care': ['OPI', 'Sally Hansen', 'Essie', 'Other'],
      'Beauty Tools': ['Dyson Supersonic', 'Revlon One-Step', 'Foreo', 'Conair', 'Other'],
      'Personal Hygiene': ['Colgate', 'Crest', 'Oral-B', 'Listerine', 'Sensodyne', 'Other'],
      'Other': ['Other'],
    },
    'Health & Wellness': {
      'Vitamins': ['Nature\'s Bounty', 'Centrum', 'Nature Made', 'Vitafusion', 'Garden of Life', 'Other'],
      'Supplements': ['GNC', 'Optimum Nutrition', 'MuscleTech', 'NOW Foods', 'Myprotein', 'Other'],
      'First Aid': ['Band-Aid', 'Neosporin', 'Johnson & Johnson', 'Curad', 'Other'],
      'Medical Devices': ['Medtronic', 'Philips Healthcare', 'GE HealthCare', 'Omron', 'Other'],
      'Face Masks': ['3M', 'Honeywell', 'Kimberly-Clark', 'Other'],
      'Blood Pressure Monitors': ['Omron', 'Withings', 'Beurer', 'iHealth', 'Other'],
      'Thermometers': ['Braun', 'iHealth', 'Vicks', 'Exergen', 'Other'],
      'Fitness Equipment': ['Peloton', 'Bowflex', 'NordicTrack', 'Sunny Health', 'Rogue Fitness', 'Other'],
      'Weight Management': ['WeightWatchers', 'SlimFast', 'Optavia', 'Herbalife', 'Other'],
      'Sexual Wellness': ['Durex', 'Trojan', 'LELO', 'K-Y', 'Other'],
      'Mobility Aids': ['Drive DeVilbiss Healthcare', 'Invacare', 'Pride Mobility', 'Other'],
      'Health Monitoring Devices': ['Fitbit', 'Apple Watch', 'Garmin', 'Whoop', 'Oura', 'Other'],
      'Other': ['Other'],
    },
    'Agriculture': {
      'Seeds': ['Corteva (Pioneer)', 'Monsanto (Bayer)', 'Syngenta', 'Burpee', 'Other'],
      'Fertilizers': ['Miracle-Gro', 'Scotts', 'Yara', 'Milorganite', 'Other'],
      'Pesticides': ['Bayer CropScience', 'Syngenta', 'BASF', 'FMC', 'Other'],
      'Herbicides': ['Roundup', 'Bayer', 'BASF', 'Dow AgroSciences', 'Other'],
      'Farm Tools': ['Fiskars', 'John Deere Tools', 'Corona', 'True Temper', 'Other'],
      'Irrigation Equipment': ['Netafim', 'Rain Bird', 'Hunter Industries', 'Toro', 'Other'],
      'Animal Feed': ['Purina Animal Nutrition', 'Cargill', 'Nutrena', 'Land O\'Lakes', 'Other'],
      'Livestock': ['ABS Global', 'Genus PLC', 'CRI (Cooperative Resources)', 'Other'],
      'Poultry Equipment': ['Big Dutchman', 'Chore-Time', 'Val-Co', 'Other'],
      'Fish Farming': ['Pentair AES', 'Skretting', 'Zeigler Bros', 'Other'],
      'Greenhouse Equipment': ['Ludvig Svensson', 'Rough Brothers', 'Atlas Greenhouse', 'Other'],
      'Farm Machinery': ['John Deere', 'Case IH', 'New Holland', 'Massey Ferguson', 'Kubota', 'Claas', 'Other'],
      'Beekeeping': ['Dadant & Sons', 'Mann Lake', 'Brushy Mountain', 'Other'],
      'Veterinary Supplies': ['Zoetis', 'Boehringer Ingelheim', 'Merck Animal Health', 'Elanco', 'Other'],
      'Other': ['Other'],
    },
    'Vehicles': {
      'Cars': ['Toyota', 'Honda', 'Ford', 'BMW', 'Mercedes-Benz', 'Hyundai', 'Nissan', 'Volkswagen', 'Chevrolet', 'Kia', 'Audi', 'Tesla', 'Other'],
      'Motorcycles': ['Harley-Davidson', 'Honda Moto', 'Yamaha', 'Kawasaki', 'Ducati', 'BMW Motorrad', 'KTM', 'Other'],
      'Bicycles': ['Trek', 'Specialized', 'Giant', 'Cannondale', 'Santa Cruz', 'Scott', 'Bianchi', 'Other'],
      'Trucks': ['Ford F-Series', 'Chevrolet Silverado', 'RAM Trucks', 'GMC Sierra', 'Toyota Tundra', 'Other'],
      'Buses': ['Volvo Buses', 'Mercedes-Benz Buses', 'Scania', 'Blue Bird', 'Other'],
      'Tractors': ['John Deere', 'Kubota', 'Mahindra', 'New Holland', 'Massey Ferguson', 'Other'],
      'Vehicle Parts': ['Bosch', 'Denso', 'ACDelco', 'Magna', 'NGK', 'Brembo', 'Other'],
      'Tires': ['Michelin', 'Bridgestone', 'Goodyear', 'Continental', 'Pirelli', 'Dunlop', 'Hankook', 'Other'],
      'Batteries': ['Interstate Batteries', 'Optima Batteries', 'DieHard', 'Varta', 'Bosch', 'Other'],
      'Oils & Lubricants': ['Mobil 1', 'Castrol', 'Shell Rotella', 'Valvoline', 'Pennzoil', 'Liqui Moly', 'Other'],
      'Car Electronics': ['Pioneer', 'Kenwood', 'Alpine', 'Sony Car Audio', 'JVC', 'Other'],
      'Car Accessories': ['WeatherTech', 'Yeti', 'Thule', 'Yakima', 'Other'],
      'Vehicle Tools': ['Snap-on', 'Craftsman', 'Mac Tools', 'Husky', 'DeWalt', 'Other'],
      'Other': ['Other'],
    },
    'Construction & Hardware': {
      'Cement': ['LafargeHolcim', 'CEMEX', 'HeidelbergCement', 'Cemex', 'Other'],
      'Bricks & Blocks': ['Wienerberger', 'Boral', 'Acme Brick', 'Other'],
      'Roofing Materials': ['GAF', 'Owens Corning', 'CertainTeed', 'Other'],
      'Paint': ['Sherwin-Williams', 'Benjamin Moore', 'Behr', 'Valspar', 'PPG', 'Dulux', 'Other'],
      'Plumbing Supplies': ['Moen', 'Kohler', 'Delta', 'SharkBite', 'Charlotte Pipe', 'Other'],
      'Electrical Supplies': ['Schneider Electric', 'Legrand', 'Leviton', 'Eaton', 'ABB', 'Other'],
      'Hand Tools': ['Stanley', 'Craftsman', 'Estwing', 'Channellock', 'Klein Tools', 'Irwin', 'Other'],
      'Power Tools': ['DeWalt', 'Milwaukee', 'Makita', 'Bosch', 'Ryobi', 'Black+Decker', 'Craftsman', 'Rigid', 'Other'],
      'Safety Equipment': ['3M', 'Honeywell Safety', 'MSA Safety', 'Ansell', 'Other'],
      'Doors & Windows': ['Andersen', 'Pella', 'Jeld-Wen', 'Marvin', 'Other'],
      'Tiles': ['Mohawk Industries', 'Daltile', 'Marazzi', 'Other'],
      'Timber': ['Weyerhaeuser', 'Georgia-Pacific', 'West Fraser', 'Other'],
      'Steel': ['ArcelorMittal', 'Nucor', 'US Steel', 'Nippon Steel', 'Other'],
      'Fasteners': ['Simpson Strong-Tie', 'Hillman', 'Grip-Rite', 'Other'],
      'Welding Equipment': ['Lincoln Electric', 'Miller Electric', 'ESAB', 'Hobart', 'Other'],
      'Other': ['Other'],
    },
    'Books & Education': {
      'Textbooks': ['Pearson', 'McGraw Hill', 'Cengage', 'HMH', 'Oxford University Press', 'Other'],
      'Children\'s Books': ['Scholastic', 'Penguin Kids', 'Dr. Seuss Enterprises', 'Disney', 'Usborne', 'Other'],
      'Fiction': ['Penguin Random House', 'HarperCollins', 'Simon & Schuster', 'Macmillan', 'Hachette', 'Other'],
      'Non-Fiction': ['HarperCollins', 'Penguin Press', 'National Geographic', 'Norton', 'Basic Books', 'Other'],
      'Religious Books': ['Zondervan', 'Thomas Nelson', 'Deseret Book', 'Crossway', 'Other'],
      'Business Books': ['Harvard Business Review (HBR) Press', 'Wiley', 'Kogan Page', 'Portfolio', 'Other'],
      'Educational Materials': ['McGraw Hill Education', 'Scholastic Classroom', 'Kaplan', 'Princeton Review', 'Other'],
      'School Supplies': ['Crayola', 'Fiskars Kids', 'Elmer\'s', 'Five Star', 'Dixon Ticonderoga', 'Other'],
      'Office Stationery': ['Mead', 'Bic', 'Paper Mate', 'Five Star', 'Pilot', 'Other'],
      'Dictionaries': ['Merriam-Webster', 'Oxford University Press', 'Collins', 'Cambridge', 'Other'],
      'E-books': ['Amazon Kindle', 'Kobo', 'Google Play Books', 'Apple Books', 'Barnes & Noble Nook', 'Other'],
      'Other': ['Other'],
    },
    'Sports & Outdoors': {
      'Football': ['Wilson', 'Adidas', 'Nike', 'Under Armour', 'Spalding', 'Puma', 'Select', 'Other'],
      'Basketball': ['Spalding', 'Wilson', 'Molten', 'Nike', 'Jordan', 'Baden', 'Other'],
      'Volleyball': ['Mikasa', 'Tachikara', 'Baden', 'Molten', 'Mizuno', 'Other'],
      'Tennis': ['Wilson', 'Babolat', 'Head', 'Yonex', 'Penn', 'Prince', 'Dunlop', 'Other'],
      'Gym Equipment': ['Life Fitness', 'Rogue Fitness', 'Matrix', 'Bowflex', 'Technogym', 'Hammer Strength', 'Other'],
      'Fitness Accessories': ['Under Armour', 'Fitbit', 'Nike', 'Lululemon', 'Gymshark', 'Other'],
      'Camping Gear': ['Coleman', 'REI Co-op', 'Yeti', 'The North Face', 'MSR', 'Osprey', 'Other'],
      'Fishing Equipment': ['Shimano', 'Daiwa', 'Penn Fishing', 'Abu Garcia', 'Ugly Stik', 'Other'],
      'Cycling': ['Specialized', 'Trek', 'Giant', 'Cannondale', 'Shimano', 'SRAM', 'Other'],
      'Outdoor Clothing': ['Patagonia', 'The North Face', 'Columbia', 'Arc\'teryx', 'Marmot', 'Other'],
      'Swimming': ['Speedo', 'TYR', 'Arena', 'Intex', 'Finis', 'Other'],
      'Hiking': ['Salomon', 'Merrell', 'Keen', 'Columbia', 'Osprey', 'Lowa', 'Other'],
      'Other': ['Other'],
    },
    'Baby & Kids': {
      'Baby Clothing': ['Carter\'s', 'Gerber Childrenswear', 'BabyGap', 'H&M Kids', 'Zara Kids', 'Other'],
      'Baby Shoes': ['Robeez', 'Stride Rite', 'Carter\'s Shoes', 'Nike Kids', 'Adidas Kids', 'Other'],
      'Diapers': ['Pampers', 'Huggies', 'Luvs', 'The Honest Company', 'Seventh Generation', 'Other'],
      'Baby Food': ['Gerber', 'Beech-Nut', 'Plum Organics', 'Happy Baby', 'Ella\'s Kitchen', 'Other'],
      'Feeding Supplies': ['Dr. Brown\'s', 'Philips Avent', 'Munchkin', 'Tommee Tippee', 'NUK', 'Medela', 'Other'],
      'Strollers': ['Bugaboo', 'Graco', 'UPPAbaby', 'Chicco', 'Baby Jogger', 'Britax', 'Other'],
      'Car Seats': ['Graco', 'Chicco', 'Britax', 'Nuna', 'Evenflo', 'Maxi-Cosi', 'Other'],
      'Toys': ['LEGO', 'Mattel (Barbie/Hot Wheels)', 'Hasbro', 'Fisher-Price', 'Melissa & Doug', 'Nerf', 'Other'],
      'School Bags': ['JanSport', 'Skip Hop', 'Pottery Barn Kids', 'Adidas Kids', 'Nike Kids', 'Other'],
      'Children\'s Furniture': ['Delta Children', 'Pottery Barn Kids', 'IKEA Kids', 'Stokke', 'Other'],
      'Baby Care Products': ['Johnson\'s Baby', 'Aveeno Baby', 'Mustela', 'Aquaphor', 'Sudocrem', 'Other'],
      'Other': ['Other'],
    },
    'Food & Beverages': {
      'Restaurants': ['Olive Garden', 'Applebee\'s', 'Chili\'s', 'Texas Roadhouse', 'Other'],
      'Fast Food': ['McDonald\'s', 'Subway', 'Starbucks', 'Burger King', 'KFC', 'Wendy\'s', 'Pizza Hut', 'Domino\'s', 'Other'],
      'Bakery': ['Cinnabon', 'Panera Bread', 'Entenmann\'s', 'Sara Lee', 'Other'],
      'Cakes': ['Betty Crocker', 'Duncan Hines', 'Pillsbury', 'Nothing Bundt Cakes', 'Other'],
      'Coffee': ['Starbucks', 'Dunkin\'', 'Peet\'s Coffee', 'Nespresso', 'Folgers', 'Lavazza', 'Nescafe', 'Other'],
      'Tea': ['Lipton', 'Twinings', 'Yogi Tea', 'Bigelow', 'Tazo', 'Tetley', 'Other'],
      'Soft Drinks': ['Coca-Cola', 'Pepsi', 'Dr Pepper', 'Sprite', 'Fanta', '7UP', 'Mountain Dew', 'Other'],
      'Juices': ['Tropicana', 'Simply Orange', 'Ocean Spray', 'Welch\'s', 'Minute Maid', 'Other'],
      'Bottled Water': ['Evian', 'Fiji Water', 'Aquafina', 'Dasani', 'Nestle Pure Life', 'Perrier', 'San Pellegrino', 'Other'],
      'Energy Drinks': ['Red Bull', 'Monster Energy', 'Rockstar', 'Celsius', 'Gatorade', 'Other'],
      'Local Foods': ['Uber Eats', 'Doordash', 'Grubhub', 'Other'],
      'Catering': ['Compass Group', 'Aramark', 'Sodexo', 'Other'],
      'Other': ['Other'],
    },
    'Pets & Animals': {
      'Dog Food': ['Royal Canin', 'Blue Buffalo', 'Purina Pro Plan', 'Hill\'s Science Diet', 'Orijen', 'Acana', 'Other'],
      'Cat Food': ['Fancy Feast', 'Friskies', 'Royal Canin Cat', 'Purina ONE Cat', 'Whiskas', 'Sheba', 'Other'],
      'Bird Supplies': ['Kaytee', 'ZuPreem', 'Hartz', 'Other'],
      'Fish Supplies': ['Tetra', 'Fluval', 'API (Aquarium Pharmaceuticals)', 'Other'],
      'Pet Accessories': ['Kong', 'Ruffwear', 'Frisco', 'Kurgo', 'Other'],
      'Pet Toys': ['BarkBox', 'Kong Toys', 'Chuckit!', 'Nylabone', 'Other'],
      'Pet Grooming': ['Wahl Clipper (Pet)', 'FURminator', 'Oster', 'Burt\'s Bees Pets', 'Other'],
      'Pet Medicines': ['Frontline', 'Heartgard', 'NexGard', 'Bravecto', 'Apoquel', 'Other'],
      'Animal Housing': ['Midwest Homes for Pets', 'Prevue Pet Products', 'Petmate', 'Other'],
      'Livestock Supplies': ['Tarter USA', 'Tractor Supply Co.', 'Behlen Country', 'Other'],
      'Other': ['Other'],
    },
    'Office Supplies': {
      'Paper': ['Hammermill', 'HP Papers', 'Georgia-Pacific', 'Xerox', 'Other'],
      'Pens & Pencils': ['Bic', 'Pilot', 'Paper Mate', 'Uni-ball', 'Pentel', 'Ticonderoga', 'Sharpie', 'Other'],
      'Notebooks': ['Moleskine', 'Five Star', 'Mead', 'Leuchtturm1917', 'Rhodia', 'Clairefontaine', 'Other'],
      'Filing Supplies': ['Smead', 'Pendaflex', 'Avery', 'Other'],
      'Office Furniture': ['Steelcase', 'Herman Miller', 'Haworth', 'HON', 'IKEA', 'Other'],
      'Office Electronics': ['Brother', 'HP', 'Canon', 'Epson', 'Casio', 'Other'],
      'Ink & Toner': ['HP', 'Epson', 'Brother', 'Canon', 'Xerox', 'Other'],
      'Calculators': ['Texas Instruments', 'Casio', 'HP', 'Sharp', 'Other'],
      'Whiteboards': ['Quartet', 'Expo', 'Ubrands', 'Other'],
      'Office Storage': ['Fellowes', 'Rubbermaid', 'Bankers Box', 'Other'],
      'Other': ['Other'],
    },
    'Entertainment': {
      'Musical Instruments': ['Fender', 'Gibson', 'Yamaha Music', 'Ibanez', 'Roland', 'Korg', 'Shure', 'Martin', 'Other'],
      'Movies': ['Walt Disney Pictures', 'Warner Bros.', 'Universal Pictures', 'Paramount', 'Sony Pictures', 'Netflix', 'Other'],
      'Music': ['Universal Music Group', 'Sony Music', 'Warner Music Group', 'Spotify', 'Apple Music', 'Other'],
      'Video Games': ['Nintendo', 'Electronic Arts (EA)', 'Activision Blizzard', 'Ubisoft', 'Take-Two', 'Square Enix', 'Other'],
      'Board Games': ['Hasbro', 'Mattel Games', 'Asmodee', 'Ravensburger', 'Catan Studio', 'Other'],
      'Toys': ['Mattel', 'LEGO Group', 'Hasbro', 'Spin Master', 'Bandai', 'Funko', 'Other'],
      'Party Supplies': ['Party City', 'Unique Industries', 'Creative Converting', 'Other'],
      'Event Equipment': ['JBL Professional', 'Yamaha Pro Audio', 'Shure', 'Chauvet DJ', 'Pioneer DJ', 'Other'],
      'Karaoke Systems': ['Singing Machine', 'VocoPro', 'Grand Videoke', 'Other'],
      'Streaming Devices': ['Roku', 'Amazon Fire TV', 'Apple TV', 'Google Chromecast', 'Nvidia Shield', 'Other'],
      'Other': ['Other'],
    },
    'Services': {
      'Cleaning Services': ['Merry Maids', 'The Maids', 'Molly Maid', 'Other'],
      'Plumbing': ['Roto-Rooter', 'Mr. Rooter', 'Benjamin Franklin Plumbing', 'Other'],
      'Electrical Services': ['Mr. Electric', 'Lemberg', 'Mister Sparky', 'Other'],
      'Carpentry': ['Handyman Connection', 'Mr. Handyman', 'House Doctors', 'Other'],
      'Painting': ['CertaPro Painters', 'Five Star Painting', '360° Painting', 'Other'],
      'Computer Repair': ['Geek Squad', 'uBreakiFix', 'Rescuecom', 'Other'],
      'Phone Repair': ['uBreakiFix', 'CPR Cell Phone Repair', 'Apple Support', 'Other'],
      'Graphic Design': ['99designs', 'Fiverr Pro', 'Upwork Enterprise', 'Canva', 'Other'],
      'Photography': ['Shutterfly', 'Getty Images Creative', 'Portrait Innovations', 'Other'],
      'Videography': ['Getty Images Video', 'Shutterstock Custom', 'Vimeo Enterprise', 'Other'],
      'Event Planning': ['Cvent', 'Bizzabo', 'Eventbrite Organizers', 'Other'],
      'Catering': ['Aramark', 'Sodexo Catering', 'Compass Group', 'Other'],
      'Laundry': ['Tide Cleaners', 'Laundromat', 'DryClean Depot', 'Other'],
      'Transport': ['Uber', 'Lyft', 'BlaBlaCar', 'Other'],
      'Delivery': ['FedEx', 'UPS', 'DHL', 'Amazon Logistics', 'Other'],
      'Tutoring': ['Kumon', 'Sylvan Learning', 'Varsity Tutors', 'Princeton Review', 'Other'],
      'Legal Services': ['LegalZoom', 'Rocket Lawyer', 'UpCounsel', 'Other'],
      'Accounting': ['H&R Block', 'TurboTax Live', 'Ernst & Young (EY)', 'PwC', 'Other'],
      'Consultancy': ['McKinsey & Company', 'Boston Consulting Group (BCG)', 'Bain & Company', 'Other'],
      'Beauty Services': ['Ulta Beauty Salon', 'Supercuts', 'Regis Salon', 'Drybar', 'Other'],
      'Other': ['Other'],
    },
    'Industrial Equipment': {
      'Generators': ['Generac', 'Caterpillar (CAT)', 'Cummins', 'Honda Power Equipment', 'Kohler', 'Other'],
      'Air Compressors': ['Ingersoll Rand', 'Atlas Copco', 'Campbell Hausfeld', 'DeWalt', 'Sullair', 'Other'],
      'Welding Machines': ['Miller Electric', 'Lincoln Electric', 'Hobart', 'ESAB', 'Other'],
      'Water Pumps': ['Grundfos', 'Goulds Water Technology', 'Flotec', 'Pedrollo', 'Other'],
      'Factory Machinery': ['Siemens', 'ABB', 'Mitsubishi Electric', 'Bosch Rexroth', 'Schneider Electric', 'Other'],
      'Packaging Equipment': ['Syntegon (Bosch Packaging)', 'Multivac', 'Sealed Air', 'Other'],
      'Laboratory Equipment': ['Thermo Fisher Scientific', 'Agilent Technologies', 'VWR', 'Shimadzu', 'Other'],
      'Solar Equipment': ['Canadian Solar', 'First Solar', 'SunPower', 'Enphase Energy', 'Jinko Solar', 'Growatt', 'Other'],
      'Heavy Machinery': ['Caterpillar (CAT)', 'Komatsu', 'John Deere Construction', 'Volvo CE', 'Hitachi', 'JCB', 'Other'],
      'Forklifts': ['Toyota Material Handling', 'Hyster-Yale', 'Crown Equipment', 'Linde', 'Other'],
      'Industrial Tools': ['Hilti', 'Milwaukee Tool', 'Proto', 'Ingersoll Rand Tools', 'Snap-on', 'Other'],
      'Safety Equipment': ['Honeywell', '3M Safety', 'MSA Safety', 'Ansell Industrial', 'DuPont', 'Other'],
      'Electrical Motors': ['Baldor-Reliance (ABB)', 'WEG', 'Nidec Motor', 'Siemens', 'Other'],
      'Manufacturing Equipment': ['Fanuc Robotics', 'Yaskawa Motoman', 'KUKA', 'ABB Robotics', 'Other'],
      'Other': ['Other'],
    },
    'Other': {
      'Other': ['Other'],
    }
  };
}